image: adoptopenjdk/openjdk11:alpine

stages:
  - build



before_script:
  # Install all required dependencies
  - apk --no-cache add maven git patch bash curl
  # Setup Git
  - git config --global user.name "Friendly Matherionity CI"
  - git config --global user.email "ci@git.matherion.dev"
  # Submodules
  - git submodule update --init --recursive

maven-build:
  stage: build
  script: "./tuinity jar"
  artifacts:
    paths:
      - Tuinity-Server/target/*.jar
      - Tuinity-API/target/*.jar