name: Build 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8,11,15]
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch Tuinity
      run: |
        git config --global user.email "ci@git.matherion.dev"
        git config --global user.name "Friendly Matherionity CI"
        git submodule update --init --recursive
        ./tuinity jar
  
    - name: Upload API artifact
      uses: actions/upload-artifact@v2
      with:
        name: matherionity-1.16.5-api.jar
        path: Tuinity-API/target/matherionity-api.jar
       
    - name: Upload server artifact
      uses: actions/upload-artifact@v2
      with:
        name: matherionity-1.16.5-server.jar
        path: Tuinity-Server/target/matherionity-1.16.5.jar
